### PR TITLE
Release notes for 8 Aug

### PR DESCRIPTION
**Pull request by carusooo**

### CODE REVIEW

**Review by eriis1 — APPROVED** [review]

**Comment by carusooo** [comment]
@bensonlee5 anything else you want to add here?

**Comment by bensonlee5** [comment]
@eriis1 (maybe in a separate PR) - can you add a short snippet to demo how to query from an agent?  I think it prob would go on [sdk/markdowns/AgentDataModels](https://docs.ganymede.bio/sdk/markdowns/AgentDataModels)

**Comment by bensonlee5** [comment]
> @eriis1 (maybe in a separate PR) - can you add a short snippet to demo how to query from an agent? I think it prob would go on [sdk/markdowns/AgentDataModels](https://docs.ganymede.bio/sdk/markdowns/AgentDataModels)

just took a stab at this and am merging in; let me know if it's off (I just referenced your remote agent PR)

**Comment by carusooo** [comment]
the bigquery APIs aren't released yet

**Comment by bensonlee5** [comment]
> the bigquery APIs aren't released yet

ah ok - let me remove from docs

**Pull request merged**
